# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html

# Site
title: 极客兔兔
keyword: 极客兔兔,geektutu
description: 极客兔兔的博客，致力于分享一些技术教程和有趣的技术实践。
author: 极客兔兔
language: zh-CN

url: https://geektutu.com	
root: /
permalink: post/:title.html

# seo优化各个浏览器的验证信息
beian: 沪ICP备18001798号-1
seo_title: 极客兔兔 # 子页面的后缀，效果： 关于我 | 极客兔兔，如果与title一致，则可以不设置
seo:
  google_site_verification: X31OY0d2sKImNbS2x8-OpITWRK4nn7nZCcXe3_hA9ew
  baidu_site_verification: p7Pz3jlx4t
  ms_site_verification: 7E2AEE3378AC93764DEAB411177A21A1
  _360_site_verification: 1d1e81a1a48a1ed2e3308d7cb8e548e7 # 不能以数字开头，所以加上了下划线

# 开启博客资源的相对链接 https://hexo.io/zh-cn/docs/asset-folders
post_asset_folder: true 

# Site settings
header_icon: img/icon.png

theme: geektutu

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://git.coding.net/gzdaijie/geektutu-blog.git
  branch: coding-pages

gitalk:
  client_id: 'c1fdd456a4caae5f7df0'
  client_secret: 'b2674451e21feae50520f99337ec15d2aebe7879'
  repo: 'geektutu-blog'
  owner: 'geektutu'

# alipay wechatpay 的二维码转换的网址，不使用二维码图片，提高加载速率。
reward:
  alipay: HTTPS://QR.ALIPAY.COM/FKX060337TUXBAX9LIFJE8
  wechat: wxp://f2f0qgGBlfD1nZXjvBjievxB0z0fc0W2sBq5

related_links:
- link: https://zhuanlan.zhihu.com/geektutu
  img: img/related_links/zhihu.png
- link: https://github.com/geektutu/hexo-theme-geektutu
  img: img/related_links/github.png
- link: https://github.com/geekcircle
  img: img/related_links/geekcircle.png

# 文章末尾配置一些提示信息，可选，默认关闭
post_tips:
  find_me: true # 本站永久域名「 xx.domain 」， 也可以通过搜索「 xx 」找到我。
  zhihu_zhuanlan: https://zhuanlan.zhihu.com/geektutu # 欢迎关注我的「 知乎专栏 」，所有文章可在「 知乎APP 」查看。

widgets:
  caidan: false  # 开启彩蛋，点击屏幕会随机弹出 '点个赞','留个言'等  

# 自定义推广链接：宽度250，高度不限。
custom_ads:
- link: https://s.click.taobao.com/t?e=m%3D2%26s%3D9Csa7S69aHgcQipKwQzePCperVdZeJviEViQ0P1Vf2kguMN8XjClArjXSXgB5m891PGHrTZ9ST8Jdb9AFE%2FbvB6xlwYjnFhg5nVYzezzVJ%2B4188cs7idFXgMYfZcHopyYMsSHLWchUVtQl8vLdysepHjKlMEkHC0ZmD53N1AU7B8xG%2BjFJUNJ0vKtvaDQfYbkClB6jgC8iAz%2BYtposB6N2M%2B1FAAYg58xy%2BHtFeiN1whhQs2DjqgEA%3D%3D
  img: https://img.alicdn.com/tps/TB1FKhrOFXXXXXrXXXXXXXXXXXX-300-100.jpg

ba_auto_push: true # Baidu 自动推送，以下均为可选配置
ba_track_id: 1a0ec38c52c08db815b0046c2783b1aa # Baidu Analytics
cnzz_track_id: 1277693649 # CNZZ Analytics
google_analysis: UA-142641425-1 # Google Analytics
google_ad_client: ca-pub-9394187906225546 # Google Ad